### ISSUE TITLE
Newyork dataset

### ISSUE THREAD

**Issue by JeremyChou28** [Sam1224/STCPA#1]
Hello, I would like to ask some questions about a few files in the newyork data set you provided: 
newyork_train_x.npy, 
newyork_train_y.npy, 
newyork_train_m.npy 
are these files represent the original data set? And x represents the original incomplete data, y represents the original complete data, m represents mask matrix?
Or are these files processed after you have fixed the missing rate of 0.5? Is the missing method MCAR(missing completely at random)?
Looking forward to your reply, thank you!

**Comment by Sam1224** [comment]
Hi, thanks for your interests in our work. Regarding to your questions:
(1) For new york dataset obtained from Uber, it is originally larger but quite incomplete. For effective evaluation, we extract a smaller connected graph from the underlying road network, which is complete, for study purpose. In short, y is a complete subset.
(2) After y is obtained, we define a missing ratio to create random masks (for each data sample) and yield input x (=y * mask).
(3) The provided dataset has a missing ratio of 0.5, and the situation is MCAR.

**Comment by JeremyChou28** [comment]
> 

I see. Thank you very much.
